INSERT INTO categorias(idcategorias,nombre_categoria) VALUES (1,"categoria1");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (2,"categoria2");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (3,"categoria3");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (4,"categoria4");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (5,"categoria5");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (6,"categoria6");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (7,"categoria7");
INSERT INTO categorias(idcategorias,nombre_categoria) VALUES (8,"categoria8");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (9,"categoria9");
INSERT INTO categorias (idcategorias,nombre_categoria) VALUES (10,"categoria10");