INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (1,"ullamcorper");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (2,"risus, at fringilla purus mauris a nunc. In at");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (3,"arcu iaculis enim, sit");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (4,"Vivamus nisi.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (5,"ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (6,"at, velit. Pellentesque");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (7,"Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (8,"nec, diam. Duis mi");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (9,"fringilla est. Mauris eu");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (10,"mauris, aliquam eu, accumsan");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (11,"congue a, aliquet");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (12,"ornare. Fusce mollis. Duis sit amet diam");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (13,"dapibus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (14,"dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (15,"Phasellus ornare.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (16,"dictum");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (17,"magna a neque. Nullam ut nisi");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (18,"dolor, tempus non, lacinia at, iaculis quis,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (19,"fermentum arcu. Vestibulum ante ipsum");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (20,"Mauris quis turpis vitae purus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (21,"mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (22,"lobortis. Class aptent");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (23,"eget odio. Aliquam vulputate ullamcorper magna. Sed eu");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (24,"Sed neque. Sed eget lacus. Mauris non dui nec urna");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (25,"nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (26,"sit amet ornare lectus justo eu arcu. Morbi sit");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (27,"magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (28,"elementum, dui quis accumsan");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (29,"orci, consectetuer euismod est arcu ac orci. Ut");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (30,"ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (31,"id, mollis nec, cursus a, enim.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (32,"Nunc ut erat. Sed nunc");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (33,"leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (34,"ac risus. Morbi metus. Vivamus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (35,"dis parturient montes, nascetur ridiculus mus. Proin vel");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (36,"Nunc mauris sapien, cursus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (37,"Aliquam nec enim.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (38,"Nunc ut erat. Sed nunc est, mollis non,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (39,"faucibus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (40,"Cras dictum ultricies");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (41,"mattis. Integer eu lacus. Quisque imperdiet, erat nonummy");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (42,"consectetuer adipiscing elit. Etiam laoreet,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (43,"facilisis, magna tellus faucibus leo,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (44,"rutrum urna, nec luctus felis purus ac tellus. Suspendisse");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (45,"eu neque pellentesque");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (46,"enim consequat purus. Maecenas");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (47,"egestas,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (48,"Ut tincidunt vehicula");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (49,"purus, in");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (50,"mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (51,"cursus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (52,"mollis dui, in sodales elit");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (53,"sem mollis dui, in sodales elit erat vitae");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (54,"lobortis ultrices.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (55,"ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (56,"faucibus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (57,"auctor. Mauris vel turpis. Aliquam");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (58,"lorem ac risus. Morbi metus. Vivamus euismod urna.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (59,"tellus faucibus leo, in lobortis tellus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (60,"amet,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (61,"gravida non,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (62,"Suspendisse sagittis. Nullam vitae diam. Proin");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (63,"imperdiet ullamcorper. Duis at lacus. Quisque purus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (64,"non,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (65,"blandit at, nisi. Cum sociis natoque");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (66,"et ipsum cursus vestibulum.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (67,"libero lacus, varius et, euismod et, commodo at, libero.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (68,"Curae; Donec");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (69,"ante. Maecenas mi felis, adipiscing fringilla, porttitor");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (70,"malesuada fames ac turpis egestas. Fusce aliquet");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (71,"Nullam vitae");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (72,"at, egestas a, scelerisque");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (73,"Fusce fermentum fermentum arcu. Vestibulum ante");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (74,"lacus, varius et, euismod et, commodo at, libero.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (75,"Aliquam ornare, libero at auctor ullamcorper, nisl arcu");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (76,"sem");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (77,"cursus.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (78,"sem elit, pharetra ut, pharetra");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (79,"risus. Nunc ac sem ut dolor dapibus gravida.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (80,"netus et malesuada fames ac turpis");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (81,"arcu ac orci. Ut semper pretium neque. Morbi quis urna.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (82,"neque. Morbi quis urna. Nunc quis arcu vel quam dignissim");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (83,"risus, at fringilla");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (84,"mollis dui, in");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (85,"purus.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (86,"tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (87,"lacus, varius et,");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (88,"interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (89,"Vestibulum");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (90,"justo. Praesent luctus. Curabitur egestas nunc");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (91,"dictum eleifend, nunc risus varius orci, in consequat enim diam");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (92,"dui. Cum sociis natoque penatibus et magnis dis parturient");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (93,"sit amet");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (94,"Aliquam adipiscing lobortis risus. In");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (95,"orci lobortis augue scelerisque mollis. Phasellus libero");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (96,"tellus");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (97,"lobortis augue scelerisque mollis. Phasellus libero");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (98,"tempus eu, ligula. Aenean euismod mauris eu elit.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (99,"Nulla dignissim. Maecenas ornare egestas ligula.");
INSERT INTO `categorias` (`idcategorias`,`nombre_categoria`) VALUES (100,"semper rutrum. Fusce dolor quam, elementum at,");
