INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (1,"administracion de empresas",1);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (2,"economia",2);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (3,"administracion de empresas",3);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (4,"analisis financiero",4);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (5,"analisis financiero",5);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (6,"analisis financiero",6);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (7,"derecho",7);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (8,"administracion de empresas",8);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (9,"economia",9);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (10,"derecho",10);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (11,"administracion de empresas",11);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (12,"contaduria",12);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (13,"economia",13);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (14,"contaduria",14);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (15,"contaduria",15);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (16,"analisis financiero",16);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (17,"administracion de empresas",17);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (18,"analisis financiero",18);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (19,"derecho",19);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (20,"contaduria",20);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (21,"economia",21);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (22,"derecho",22);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (23,"derecho",23);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (24,"analisis financiero",24);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (25,"analisis financiero",25);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (26,"economia",26);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (27,"administracion de empresas",27);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (28,"contaduria",28);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (29,"administracion de empresas",29);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (30,"administracion de empresas",30);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (31,"analisis financiero",31);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (32,"derecho",32);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (33,"derecho",33);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (34,"contaduria",34);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (35,"derecho",35);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (36,"economia",36);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (37,"analisis financiero",37);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (38,"analisis financiero",38);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (39,"economia",39);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (40,"contaduria",40);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (41,"analisis financiero",41);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (42,"economia",42);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (43,"economia",43);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (44,"administracion de empresas",44);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (45,"analisis financiero",45);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (46,"derecho",46);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (47,"contaduria",47);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (48,"analisis financiero",48);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (49,"administracion de empresas",49);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (50,"derecho",50);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (51,"economia",51);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (52,"administracion de empresas",52);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (53,"administracion de empresas",53);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (54,"derecho",54);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (55,"analisis financiero",55);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (56,"economia",56);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (57,"contaduria",57);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (58,"contaduria",58);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (59,"derecho",59);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (60,"economia",60);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (61,"derecho",61);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (62,"administracion de empresas",62);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (63,"economia",63);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (64,"economia",64);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (65,"administracion de empresas",65);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (66,"analisis financiero",66);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (67,"derecho",67);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (68,"analisis financiero",68);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (69,"contaduria",69);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (70,"derecho",70);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (71,"administracion de empresas",71);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (72,"contaduria",72);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (73,"derecho",73);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (74,"derecho",74);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (75,"administracion de empresas",75);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (76,"derecho",76);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (77,"contaduria",77);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (78,"contaduria",78);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (79,"analisis financiero",79);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (80,"economia",80);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (81,"economia",81);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (82,"contaduria",82);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (83,"derecho",83);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (84,"analisis financiero",84);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (85,"analisis financiero",85);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (86,"contaduria",86);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (87,"administracion de empresas",87);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (88,"economia",88);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (89,"derecho",89);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (90,"derecho",90);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (91,"contaduria",91);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (92,"administracion de empresas",92);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (93,"contaduria",93);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (94,"contaduria",94);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (95,"administracion de empresas",95);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (96,"derecho",96);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (97,"analisis financiero",97);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (98,"administracion de empresas",98);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (99,"analisis financiero",99);
INSERT INTO estudios (idestudios,estudios,personas_idpersonas) VALUES (100,"contaduria",100);