INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (1,"vestibulum lorem, sit amet ultricies sem magna nec",1);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (2,"molestie dapibus ligula. Aliquam erat",2);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (3,"orci",3);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (4,"hendrerit. Donec porttitor tellus non magna. Nam ligula elit,",4);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (5,"Nullam vitae diam. Proin dolor. Nulla semper",5);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (6,"mauris id sapien. Cras dolor dolor,",6);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (7,"Donec sollicitudin adipiscing",7);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (8,"et, rutrum eu, ultrices sit amet, risus. Donec",8);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (9,"at arcu.",9);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (10,"diam nunc,",10);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (11,"vehicula. Pellentesque",11);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (12,"quam.",12);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (13,"quam a felis ullamcorper viverra. Maecenas iaculis",13);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (14,"dignissim magna a",14);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (15,"pellentesque. Sed dictum. Proin eget",15);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (16,"tellus, imperdiet non, vestibulum nec, euismod",16);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (17,"mi",17);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (18,"est ac mattis semper, dui",18);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (19,"velit egestas lacinia. Sed congue, elit sed",19);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (20,"Proin vel",20);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (21,"massa. Integer vitae nibh. Donec est mauris,",21);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (22,"Nullam",22);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (23,"Curae; Donec tincidunt. Donec",23);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (24,"vitae risus. Duis a",24);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (25,"pharetra sed, hendrerit a,",25);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (26,"aliquet, sem ut cursus",26);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (27,"Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",27);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (28,"ut, pellentesque eget, dictum",28);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (29,"justo sit amet nulla. Donec",29);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (30,"ridiculus mus. Proin vel arcu eu odio tristique pharetra.",30);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (31,"egestas. Duis ac arcu. Nunc mauris. Morbi non sapien",31);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (32,"augue scelerisque mollis. Phasellus libero",32);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (33,"eu nulla",33);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (34,"Quisque nonummy ipsum non arcu. Vivamus sit amet risus.",34);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (35,"vestibulum, neque sed",35);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (36,"dictum placerat,",36);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (37,"pede. Cras vulputate velit eu sem. Pellentesque",37);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (38,"dictum mi, ac mattis velit justo nec",38);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (39,"dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a",39);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (40,"Aenean massa. Integer vitae",40);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (41,"orci quis lectus. Nullam suscipit, est ac facilisis",41);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (42,"penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin",42);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (43,"vitae dolor. Donec fringilla. Donec feugiat",43);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (44,"a purus. Duis elementum, dui quis accumsan convallis, ante lectus",44);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (45,"in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet,",45);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (46,"id, libero. Donec consectetuer",46);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (47,"orci",47);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (48,"velit eu sem. Pellentesque ut ipsum ac mi",48);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (49,"ac mi eleifend egestas. Sed",49);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (50,"porttitor eros nec tellus. Nunc lectus pede, ultrices",50);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (51,"mi lacinia mattis. Integer eu lacus. Quisque",51);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (52,"dolor. Quisque tincidunt",52);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (53,"luctus, ipsum",53);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (54,"Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque",54);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (55,"risus. Donec egestas. Duis ac arcu. Nunc",55);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (56,"Nam ac nulla. In tincidunt congue",56);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (57,"feugiat. Sed nec metus facilisis",57);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (58,"purus, in molestie tortor nibh sit amet orci. Ut sagittis",58);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (59,"Quisque fringilla",59);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (60,"dictum magna. Ut tincidunt orci",60);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (61,"sodales",61);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (62,"odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque",62);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (63,"venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing",63);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (64,"nibh. Aliquam ornare, libero",64);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (65,"dui. Cum sociis natoque penatibus et magnis dis parturient montes,",65);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (66,"ut, sem. Nulla interdum. Curabitur dictum. Phasellus in",66);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (67,"varius orci, in consequat enim diam",67);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (68,"arcu. Morbi sit amet massa. Quisque porttitor",68);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (69,"molestie. Sed id risus quis diam luctus lobortis. Class aptent",69);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (70,"in felis.",70);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (71,"metus. In nec orci.",71);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (72,"justo sit amet nulla. Donec non justo. Proin non massa",72);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (73,"Proin mi. Aliquam gravida mauris ut mi. Duis risus",73);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (74,"aliquet diam. Sed diam lorem, auctor quis, tristique",74);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (75,"lorem tristique aliquet. Phasellus",75);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (76,"dolor egestas rhoncus. Proin nisl sem, consequat",76);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (77,"in consectetuer ipsum nunc id enim. Curabitur massa.",77);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (78,"Mauris nulla. Integer urna. Vivamus molestie",78);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (79,"amet, dapibus id, blandit at, nisi. Cum sociis",79);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (80,"imperdiet nec, leo. Morbi",80);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (81,"ornare lectus justo eu",81);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (82,"euismod enim. Etiam gravida molestie arcu. Sed",82);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (83,"Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed",83);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (84,"a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus",84);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (85,"risus",85);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (86,"pellentesque.",86);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (87,"ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac,",87);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (88,"Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus",88);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (89,"cursus in, hendrerit consectetuer,",89);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (90,"id, ante. Nunc mauris sapien, cursus",90);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (91,"sit amet, dapibus",91);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (92,"Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada",92);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (93,"fringilla ornare placerat, orci lacus vestibulum lorem, sit amet",93);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (94,"velit. Sed malesuada augue ut lacus. Nulla",94);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (95,"enim. Sed nulla ante,",95);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (96,"risus.",96);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (97,"ac mattis velit justo nec ante. Maecenas mi felis,",97);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (98,"sapien. Cras dolor dolor, tempus",98);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (99,"placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,",99);
INSERT INTO `estudios` (`idestudios`,`estudios`,`personas_idpersonas`) VALUES (100,"Praesent luctus. Curabitur egestas",100);
