INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (1,"cursus non, egestas a, dui. Cras pellentesque.",1,1);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (2,"rhoncus id, mollis nec, cursus a, enim. Suspendisse",2,2);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (3,"Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis",3,3);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (4,"dui, semper et, lacinia",4,4);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (5,"Vestibulum ante ipsum primis in faucibus",5,5);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (6,"in",6,6);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (7,"odio a purus. Duis elementum, dui quis accumsan",7,7);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (8,"In lorem. Donec elementum,",8,8);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (9,"tellus non magna. Nam ligula",9,9);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (10,"sit amet, consectetuer",10,10);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (11,"vitae semper egestas, urna justo",11,11);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (12,"pede blandit congue. In scelerisque scelerisque",12,12);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (13,"eu, accumsan sed, facilisis vitae, orci. Phasellus",13,13);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (14,"in felis. Nulla tempor augue ac ipsum.",14,14);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (15,"a,",15,15);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (16,"arcu ac orci.",16,16);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (17,"nisi. Aenean eget metus. In nec orci. Donec",17,17);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (18,"velit dui, semper et, lacinia vitae, sodales at,",18,18);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (19,"amet, consectetuer adipiscing elit. Aliquam auctor, velit",19,19);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (20,"leo elementum sem,",20,20);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (21,"Nulla eget metus eu",21,21);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (22,"ut odio vel est tempor bibendum. Donec felis",22,22);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (23,"vel arcu.",23,23);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (24,"amet, consectetuer adipiscing elit.",24,24);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (25,"vel, convallis in, cursus et, eros. Proin",25,25);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (26,"pede, malesuada vel,",26,26);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (27,"iaculis",27,27);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (28,"feugiat. Sed nec metus",28,28);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (29,"malesuada fringilla est. Mauris eu turpis. Nulla aliquet.",29,29);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (30,"tristique senectus et netus et malesuada fames ac",30,30);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (31,"urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis",31,31);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (32,"eros turpis non enim. Mauris quis",32,32);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (33,"Aliquam gravida",33,33);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (34,"aliquet vel, vulputate eu, odio. Phasellus at augue id",34,34);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (35,"arcu imperdiet",35,35);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (36,"vestibulum nec,",36,36);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (37,"adipiscing lobortis risus. In mi pede, nonummy",37,37);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (38,"dolor quam, elementum",38,38);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (39,"magna. Cras convallis",39,39);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (40,"In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas.",40,40);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (41,"aliquet, metus urna convallis erat, eget tincidunt",41,41);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (42,"Nam nulla magna, malesuada vel, convallis in, cursus et, eros.",42,42);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (43,"elit fermentum",43,43);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (44,"sit amet luctus",44,44);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (45,"viverra.",45,45);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (46,"nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.",46,46);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (47,"fames ac turpis",47,47);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (48,"nunc sed",48,48);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (49,"semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam",49,49);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (50,"nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet.",50,50);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (51,"lacinia. Sed congue, elit sed consequat",51,51);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (52,"ut cursus luctus,",52,52);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (53,"turpis non enim.",53,53);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (54,"Nulla semper tellus id",54,54);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (55,"est",55,55);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (56,"molestie in, tempus eu, ligula.",56,56);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (57,"lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis",57,57);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (58,"adipiscing elit. Aliquam auctor,",58,58);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (59,"sem, vitae aliquam eros turpis",59,59);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (60,"euismod",60,60);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (61,"libero. Morbi accumsan laoreet",61,61);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (62,"ligula tortor, dictum",62,62);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (63,"nulla. Donec non justo. Proin non",63,63);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (64,"Vivamus",64,64);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (65,"ullamcorper,",65,65);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (66,"consectetuer euismod est arcu ac orci. Ut",66,66);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (67,"ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae",67,67);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (68,"quis diam. Pellentesque habitant morbi tristique senectus et netus et",68,68);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (69,"eu, ultrices sit",69,69);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (70,"nisi. Cum sociis natoque penatibus",70,70);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (71,"nisi dictum augue malesuada malesuada. Integer id",71,71);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (72,"vitae diam. Proin dolor. Nulla semper tellus id nunc",72,72);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (73,"ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam",73,73);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (74,"purus. Maecenas libero est, congue",74,74);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (75,"ante lectus convallis",75,75);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (76,"Etiam laoreet, libero",76,76);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (77,"egestas lacinia.",77,77);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (78,"malesuada vel, venenatis vel, faucibus",78,78);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (79,"Morbi non sapien molestie",79,79);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (80,"magna. Ut tincidunt orci quis lectus. Nullam suscipit,",80,80);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (81,"urna convallis erat, eget tincidunt",81,81);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (82,"lacus. Etiam bibendum fermentum metus. Aenean sed",82,82);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (83,"augue eu tellus. Phasellus elit pede, malesuada vel, venenatis",83,83);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (84,"pede. Praesent eu dui. Cum sociis",84,84);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (85,"sit amet lorem",85,85);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (86,"eu lacus. Quisque imperdiet, erat nonummy ultricies",86,86);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (87,"pharetra, felis",87,87);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (88,"sed dolor. Fusce",88,88);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (89,"feugiat placerat velit. Quisque varius.",89,89);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (90,"ipsum dolor sit amet, consectetuer",90,90);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (91,"posuere vulputate, lacus. Cras interdum.",91,91);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (92,"tempus mauris erat eget ipsum.",92,92);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (93,"Donec",93,93);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (94,"nulla. In tincidunt",94,94);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (95,"semper egestas, urna",95,95);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (96,"a,",96,96);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (97,"libero nec ligula consectetuer rhoncus. Nullam",97,97);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (98,"luctus vulputate,",98,98);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (99,"purus, in molestie tortor nibh sit amet",99,99);
INSERT INTO `insumos` (`idinsumos`,`nombre_insumo`,`personas_idpersonas`,`categorias_idcategorias`) VALUES (100,"adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.",100,100);
