INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (1,"luctus et ultrices posuere cubilia Curae; Donec","Candace","tecnico",1);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (2,"egestas ligula. Nullam feugiat placerat","Josiah","contador",2);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (3,"Vivamus molestie dapibus ligula.","Arthur","tecnico",3);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (4,"magna. Sed","Constance","tecnico",4);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (5,"ornare placerat, orci lacus vestibulum lorem, sit amet","Lacota","tecnico",5);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (6,"felis eget varius ultrices, mauris ipsum porta elit, a feugiat","September","contador",6);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (7,"imperdiet dictum magna. Ut tincidunt orci quis","Brandon","contador",7);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (8,"ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec,","Dana","contador",8);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (9,"hendrerit. Donec porttitor","Emily","contador",9);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (10,"ipsum non arcu. Vivamus sit amet risus.","Mollie","tecnico",10);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (11,"amet, consectetuer","Cally","contador",11);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (12,"viverra. Maecenas iaculis aliquet","Chloe","contador",12);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (13,"convallis, ante lectus convallis est, vitae sodales nisi","Jesse","contador",13);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (14,"auctor. Mauris","Hadassah","tecnico",14);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (15,"suscipit, est ac facilisis facilisis, magna tellus faucibus","Wallace","tecnico",15);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (16,"quis, pede. Suspendisse dui. Fusce diam nunc,","Allistair","tecnico",16);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (17,"at risus. Nunc ac sem ut dolor dapibus gravida.","Willa","contador",17);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (18,"dolor,","Dahlia","contador",18);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (19,"eget","Hanna","contador",19);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (20,"augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.","Tatiana","tecnico",20);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (21,"Proin sed turpis nec","Harrison","tecnico",21);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (22,"eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus","Acton","contador",22);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (23,"Nam consequat","Adena","tecnico",23);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (24,"felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,","Leah","contador",24);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (25,"pede. Cras vulputate","Blair","contador",25);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (26,"imperdiet ullamcorper. Duis at lacus. Quisque","Baxter","contador",26);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (27,"vitae nibh. Donec","Yvonne","tecnico",27);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (28,"Vivamus non lorem vitae odio sagittis","Nola","contador",28);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (29,"enim. Sed nulla ante, iaculis nec,","Ronan","contador",29);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (30,"erat neque non quam. Pellentesque","Todd","contador",30);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (31,"tincidunt dui augue eu tellus. Phasellus elit pede, malesuada","Jenna","tecnico",31);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (32,"Donec at arcu. Vestibulum ante ipsum primis in faucibus","Dara","contador",32);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (33,"cursus et, eros.","Chester","tecnico",33);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (34,"faucibus orci luctus","Damian","tecnico",34);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (35,"magna. Cras convallis convallis dolor.","India","contador",35);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (36,"Duis a mi fringilla mi lacinia mattis. Integer","Ariana","tecnico",36);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (37,"sapien. Cras dolor","Zena","contador",37);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (38,"Nulla aliquet. Proin velit. Sed malesuada augue","Magee","contador",38);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (39,"sit amet, faucibus ut, nulla. Cras eu tellus","Xander","contador",39);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (40,"dolor","Quinlan","contador",40);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (41,"magna. Lorem ipsum dolor sit amet,","Brent","contador",41);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (42,"dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit.","Jack","contador",42);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (43,"adipiscing lacus. Ut nec","Gregory","tecnico",43);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (44,"eu erat semper rutrum. Fusce dolor quam, elementum","Eaton","tecnico",44);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (45,"nisi magna sed dui. Fusce aliquam, enim nec tempus","Julian","tecnico",45);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (46,"Duis ac","Roary","tecnico",46);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (47,"mauris elit, dictum eu, eleifend nec, malesuada ut, sem.","Chloe","contador",47);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (48,"accumsan interdum libero dui","Xaviera","contador",48);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (49,"mauris sagittis","Linus","contador",49);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (50,"magna sed dui. Fusce aliquam, enim","Lawrence","tecnico",50);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (51,"nec, diam. Duis mi enim, condimentum eget, volutpat","Ulysses","tecnico",51);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (52,"Cras convallis convallis dolor. Quisque tincidunt pede ac","Francis","tecnico",52);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (53,"vulputate velit eu sem. Pellentesque ut","Shea","tecnico",53);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (54,"semper auctor. Mauris vel turpis. Aliquam","Adam","contador",54);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (55,"mattis ornare, lectus ante dictum mi, ac mattis","Patricia","contador",55);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (56,"mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.","Hop","contador",56);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (57,"aliquam adipiscing lacus. Ut nec urna et arcu","Hanna","tecnico",57);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (58,"Vivamus","Asher","contador",58);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (59,"dis","Keegan","contador",59);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (60,"tempor augue ac ipsum. Phasellus vitae mauris sit","Brielle","contador",60);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (61,"ipsum. Donec","Lee","tecnico",61);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (62,"habitant morbi","Hayden","contador",62);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (63,"metus urna convallis","Ocean","tecnico",63);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (64,"odio sagittis","Imelda","contador",64);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (65,"lobortis, nisi nibh lacinia","Georgia","contador",65);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (66,"tempus non, lacinia at, iaculis quis,","Brynn","tecnico",66);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (67,"interdum enim non nisi.","Isabelle","tecnico",67);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (68,"ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere","Drake","tecnico",68);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (69,"scelerisque","Carlos","tecnico",69);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (70,"aliquet, sem","Fredericka","contador",70);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (71,"purus. Maecenas libero est, congue a, aliquet vel,","Nathaniel","tecnico",71);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (72,"non, hendrerit id, ante. Nunc mauris","Anika","tecnico",72);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (73,"elementum sem,","Jonas","tecnico",73);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (74,"euismod","Mira","contador",74);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (75,"ligula. Nullam feugiat placerat velit.","Louis","contador",75);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (76,"vulputate mauris sagittis placerat. Cras dictum ultricies","Nomlanga","tecnico",76);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (77,"tellus","Harding","contador",77);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (78,"Nam interdum enim","Brooke","contador",78);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (79,"nostra, per inceptos hymenaeos.","Dolan","tecnico",79);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (80,"tortor at risus. Nunc ac sem ut dolor","Barrett","contador",80);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (81,"mi lorem, vehicula et, rutrum eu, ultrices","Cain","contador",81);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (82,"non, luctus sit amet, faucibus","Audra","tecnico",82);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (83,"nunc id enim. Curabitur massa.","Uta","tecnico",83);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (84,"Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus.","Carla","contador",84);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (85,"Etiam vestibulum massa rutrum magna. Cras","Hunter","contador",85);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (86,"pede. Cras vulputate velit eu sem. Pellentesque ut ipsum","Ross","contador",86);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (87,"risus. Morbi metus.","Norman","contador",87);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (88,"sed pede. Cum sociis natoque penatibus et","Hiram","contador",88);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (89,"arcu eu","Malik","tecnico",89);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (90,"sem. Nulla interdum. Curabitur dictum. Phasellus in felis.","Alexis","tecnico",90);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (91,"leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,","Kameko","contador",91);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (92,"Donec tempor, est ac","Amaya","tecnico",92);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (93,"a, dui. Cras pellentesque. Sed dictum. Proin","Hamilton","contador",93);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (94,"aliquet, metus urna convallis erat, eget tincidunt dui","Erica","tecnico",94);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (95,"Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac","Zahir","tecnico",95);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (96,"auctor","Aristotle","contador",96);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (97,"eu enim. Etiam imperdiet dictum","Akeem","tecnico",97);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (98,"in faucibus orci luctus et ultrices","Gannon","contador",98);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (99,"id nunc interdum feugiat. Sed nec metus facilisis lorem","Baker","contador",99);
INSERT INTO `usuarios` (`idusuarios`,`contraseña`,`usuario`,`rol`,`personas_idpersonas`) VALUES (100,"Duis at lacus. Quisque purus","Audra","tecnico",100);
